version: "2.2"
x-redash-service: &redash-service
  image: andresorrego94/tablyx:v1
  depends_on:
    - redis
  restart: always
x-redash-environment: &redash-environment
  REDASH_LOG_LEVEL: "INFO"
  REDASH_REDIS_URL: "redis://redis:6379/0"
  REDASH_DATABASE_URL: "postgresql://postgres:tablyx94@database-1.cg7gwev1cdib.us-east-1.rds.amazonaws.com:5432/postgres"
  REDASH_RATELIMIT_ENABLED: "false"
  REDASH_MAIL_DEFAULT_SENDER: "redash@example.com"
  REDASH_MAIL_SERVER: "email"
  REDASH_ENFORCE_CSRF: "true"
services:
  server:
    <<: *redash-service
    command: dev_server
    depends_on:
      - redis
    ports:
      - "5000"
      - "5678"
    environment:
      <<: *redash-environment
      PYTHONUNBUFFERED: 0
  scheduler:
    <<: *redash-service
    command: dev_scheduler
    depends_on:
      - server
    environment:
      <<: *redash-environment
  worker:
    <<: *redash-service
    command: dev_worker
    depends_on:
      - server
    environment:
      <<: *redash-environment
      PYTHONUNBUFFERED: 0
  redis:
    image: redis:3-alpine
    restart: unless-stopped 
  email:
    image: djfarrelly/maildev
    ports:
      - "81"
    restart: unless-stopped
  flowengine:
    image: 367056919838.dkr.ecr.us-east-1.amazonaws.com/flowengine
    ports:
      - "80"
